- hosts: all
  roles:
    - role: preinstall
  gather_facts: yes
  remote_user: root
  serial: 1
  any_errors_fatal: true
  tags: [preinstall]

- hosts: psql
  roles:
    - role: postgres
  gather_facts: yes
  remote_user: root
  serial: 1
  any_errors_fatal: true
  tags: [postgres]

- hosts: ha
  roles:
    - role: haproxy
  gather_facts: yes
  remote_user: root
  serial: 1
  any_errors_fatal: true
  tags: [haproxy]

- hosts: ha
  roles:
    - role: keepalived
  gather_facts: yes
  remote_user: root
  serial: 1
  any_errors_fatal: true
  tags: [keepalived]