- name: Install loadbalancer packages
  apt:
    update_cache: true
    name:
      - keepalived
    state: latest
    update_cache: true

- name: Copy keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start and enable the keepalived service
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes