# General
install_ansible_modules: "true"
disable_transparent_huge_pages: "true"
setup_interface: "false"

# DNS

resolv_nameservers: [178.22.122.100, 185.51.200.2] # 403.online
use_iran: "true" # change it to "false" if you are outside of iran
# Docker

docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_key_path: "/etc/apt/keyrings/docker.gpg"
docker_apt_repo: "https://download.docker.com/linux/ubuntu"